git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\delve_concept.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\delve-concept.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\MicrosoftGraph_DevStack.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\MicrosoftGraph-DevStack.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\microsoft_graph.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\microsoft-graph.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\microsoft_graph_600.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\microsoft-graph-600.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\microsoft_graph_800.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\microsoft-graph-800.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\msgraph_auth_resource_access.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\msgraph-auth-resource-access.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\MSGraph_DevStack_v2Auth.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\MSGraph-DevStack-v2Auth.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\peoplecard_concept.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\peoplecard-concept.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\security_dataflow_1.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\security-dataflow-1.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\security_overview_diagram_1.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\security-overview-diagram-1.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\splunk_search_query.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\splunk-search-query.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\splunk_search_results.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\splunk-search-results.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\splunk_search_timeline.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\splunk-search-timeline.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\Teams_GraphAPIUsage.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\Teams-GraphAPIUsage.png
git mv C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\teams_lifecycle.png C:\Users\jerem\Documents\GitHub\microsoft-graph-docs\concepts\images\teams-lifecycle.png
